In [1]:
import numpy as np

In [2]:
#Creating numpy array from python list
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
#Multi-dimensional array
matrix = np.array([[1,2],[3,4],[5,6]])
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
print(np.zeros((3,3)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(5,25,5)

array([ 5., 10., 15., 20., 25.])

In [10]:
#Array Attributes
a = np.array([[1,2,3],[4,5,6]])
print(a.shape) #shape of array
print(a.ndim) #dimension of array
print(a.size) #Total number of element
print(a.dtype) #data type of element

(2, 3)
2
6
int64


In [11]:
b = np.array([[1,2,3,4,5]])
print(b.shape)
print(b.ndim)
print(b.size)
print(b.dtype)

(1, 5)
2
5
int64


In [12]:
#Indexing and Slicing
a = np.array([10,20,30,40,50])
print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]


In [13]:
#2D Slicing
b = np.array([[1,2,3],[4,5,6]])
print(b[0,1])
print(b[:,1])
print(b[1,:])

2
[2 5]
[4 5 6]


In [14]:
#Array Operations
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.array([25,49,64])

print(a + b)
print(a * b)
print(a * 2)
print(np.sqrt(a))
print(np.sqrt(c))

[11 22 33]
[10 40 90]
[2 4 6]
[1.         1.41421356 1.73205081]
[5. 7. 8.]


In [15]:
a = np.array([[1],[2],[3]])
b =np.array([10,20,30])
print (a + b)
print(a.shape)
print(b.shape)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
(3, 1)
(3,)


In [16]:
#Reshaping and Flattening
a = np.arange(6).reshape(2,3)
print(a)
 
b = a.flatten()
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [17]:
a = np.array([1,2,3,4,5])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a)) #Standard deviation
print(np.median(a))


15
3.0
1
5
1.4142135623730951
3.0


In [18]:
#Numpy doesn't have a built-in mode function directly, but Scipy does
from scipy import stats
arr = np.array([1,2,2,3,4,5,5,5,6])
print(stats.mode(arr,keepdims=True).mode[0])

5


In [19]:
#Random module
np.random.seed(0) #This sets the random number generator seed to 0 to make sure that every time we run the code, we get the same random numbers. it's used for reproducibility
print(np.random.rand(2,2)) # This generates a 2*2 array of random floats from a uniform distribution over [0,1]
print(np.random.randint(0,10,5))# Generate 5 Random ints between 0 and 9

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
[9 3 5 2 4]
